#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor 0x0020000A  -d I II III IV 
bspc monitor 0x0020000C -d V VI VII
xrandr --output DP-1 --mode  1366x768 --rate 60.00 --output VGA1 
xrandr --output HDMI-1 --primary  --mode 1366x768 --rate 60.00 --left-of DP-1

/home/vnmsnake/.config/polybar/blocks/launch.sh &
/home/vnmsnake/.config/polybar/forest/launch.sh &
picom &
feh --bg-fill --randomize /home/vnmsnake/wall/*

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
